Solution creation flow
ELEVATE-Project/samiksha-service pull request #23
Opened 2024-05-31 05:04 UTC by praveenKDass

2024-06-06 06:02 UTC, VISHNUDAS-tunerlabs requested changes
reviewed 8 files added comments based on that

2024-06-18 16:34 UTC, praveenKDass commented on controllers/v1/programsController.js
> +   /**
Changed the URl as /samiksha/v1/programs/ in all the places @VISHNUDAS-tunerlabs

2024-06-18 16:35 UTC, praveenKDass commented on controllers/v1/programsController.js
> +  // async list(req) {
Removed the commented code

2024-06-18 16:35 UTC, praveenKDass commented on controllers/v1/programsController.js
>    async list(req) {
For list not required validator so didn't add for it but for other program APIs added the validator @VISHNUDAS-tunerlabs

2024-06-18 16:37 UTC, praveenKDass commented on controllers/v1/programsController.js
> +          req.pageNo,
So middleware will convert req.query.page to req.pageNo and same for limit so keep it like that and also while testing the API pagination worked correctly @VISHNUDAS-tunerlabs

2024-06-18 16:38 UTC, praveenKDass commented on controllers/v1/programsController.js
> +
Added api doc @VISHNUDAS-tunerlabs

2024-06-18 16:39 UTC, praveenKDass commented on controllers/v1/programsController.js
> +   async create(req) {
Added validator for create @VISHNUDAS-tunerlabs

2024-06-18 16:39 UTC, praveenKDass commented on controllers/v1/programsController.js
> +          req.body,
added the comment @VISHNUDAS-tunerlabs

2024-06-18 16:39 UTC, praveenKDass commented on controllers/v1/programsController.js
> +   /**
Added API document for update @VISHNUDAS-tunerlabs

2024-06-18 16:40 UTC, praveenKDass commented on controllers/v1/programsController.js
> +   async update(req) {
added validator @VISHNUDAS-tunerlabs

2024-06-18 16:40 UTC, praveenKDass commented on controllers/v1/programsController.js
> +          req.params._id,
Added comment for boolean value which passing in arg @VISHNUDAS-tunerlabs

2024-06-18 16:41 UTC, praveenKDass commented on controllers/v1/programsController.js
> +
added api document @VISHNUDAS-tunerlabs

2024-06-18 16:41 UTC, praveenKDass commented on controllers/v1/programsController.js
> +    async addRolesInScope(req) {
added validator for  addRolesInScope Api @VISHNUDAS-tunerlabs

2024-06-18 16:42 UTC, praveenKDass commented on controllers/v1/programsController.js
> +        /**
added @VISHNUDAS-tunerlabs

2024-06-18 16:42 UTC, praveenKDass commented on controllers/v1/programsController.js
> +  async addEntitiesInScope(req) {
added the validator @VISHNUDAS-tunerlabs

2024-06-18 16:43 UTC, praveenKDass commented on controllers/v1/programsController.js
> +     /**
Added api document @VISHNUDAS-tunerlabs

2024-06-18 16:43 UTC, praveenKDass commented on controllers/v1/programsController.js
> +     async removeRolesInScope(req) {
added validator @VISHNUDAS-tunerlabs

2024-06-18 16:44 UTC, praveenKDass commented on controllers/v1/programsController.js
> +    * @api {post} /assessment/api/v1/programs/removeEntitiesInScope/:programId Add roles in programs
changed to  /samiksha/v1/programs/removeEntitiesInScope @VISHNUDAS-tunerlabs

2024-06-18 16:44 UTC, praveenKDass commented on controllers/v1/programsController.js
> +  async removeEntitiesInScope(req) {
its required and added in program module validator file @VISHNUDAS-tunerlabs

2024-06-18 16:45 UTC, praveenKDass commented on controllers/v1/programsController.js
> +    * @api {get} /assessment/api/v1/programs/details/:programId Program Details
Changed url to  /samiksha/v1/programs/details @VISHNUDAS-tunerlabs

2024-06-18 16:45 UTC, praveenKDass commented on controllers/v1/programsController.js
> +     async details(req) {
added validator @VISHNUDAS-tunerlabs

2024-06-18 16:46 UTC, praveenKDass commented on controllers/v1/programsController.js
> +   async join(req) {
Added validator for join api @VISHNUDAS-tunerlabs

2024-06-18 16:49 UTC, praveenKDass commented on controllers/v1/programsController.js
> +    return new Promise(async (resolve, reject) => {
Only for this function and details removed that and used only async await method @VISHNUDAS-tunerlabs ..its working as expected if we want keep that way in future we will create a new ticket for that and will make the change..let me know your idea or if need any changes @VISHNUDAS-tunerlabs

2024-06-18 16:49 UTC, praveenKDass commented on controllers/v1/programsController.js
>    /**
Changed URLs @VISHNUDAS-tunerlabs

2024-06-18 16:55 UTC, praveenKDass commented on generics/messageConstants/endpoints.js
> +  USER_CONSENT_API: '/v1/user/consent/update',
No we were only using  GET_LOCATION_DATA,and  USER_READ_V5 and  USER_CONSENT_API on this i have some doubts will connect over the call for this @VISHNUDAS-tunerlabs

2024-06-18 16:56 UTC, praveenKDass commented on generics/services/users.js
> +const locationSearch = function (
Yes moved to entity-management service @VISHNUDAS-tunerlabs

2024-06-18 16:56 UTC, praveenKDass commented on generics/services/users.js
> +const profile = function ( token,userId = "" ) {
Yes @VISHNUDAS-tunerlabs .its working i can able to fetch the user info

2024-06-18 16:59 UTC, praveenKDass commented on generics/services/users.js
> +const orgSchoolSearch = function (filterData, pageSize = '', pageNo = '', searchKey = '', fields = []) {
Yes we were not using this API call  But i need a small doubt over that. will connect for this and endpoint comment @VISHNUDAS-tunerlabs

2024-06-18 17:00 UTC, praveenKDass commented on module/programs/helper.js
> +        let programData = await database.models.programs.find(queryObject, projection, pagination).lean();
Added a databaseQuery @VISHNUDAS-tunerlabs

2024-06-18 17:01 UTC, praveenKDass commented on module/programs/helper.js
> +    return new Promise(async (resolve, reject) => {
moved it to databaseQuery file @VISHNUDAS-tunerlabs

2024-06-18 17:02 UTC, praveenKDass commented on module/programs/helper.js
> +        programData = _.omit(programData, ['scope', 'userId']);
intergrated as mentioned @VISHNUDAS-tunerlabs

2024-07-16 09:56 UTC, closed without merging