Feature/form api
ELEVATE-Project/samiksha-service pull request #80
Opened 2024-10-07 12:32 UTC by borkarsaish65

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs requested changes
@borkarsaish65 reviewed on Oct 7

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/formsController.js
> +	 * @api {post} /project/v1/forms/create
@borkarsaish65 wrong url

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/formsController.js
> +	 * @apiSampleRequest /project/v1/forms/create
@borkarsaish65 correctthe url

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/formsController.js
> +	 * @api {post} /project/v1/forms/update/:_id
@borkarsaish65 Please correct the url

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/formsController.js
> +	 * @apiSampleRequest /project/v1/forms/update/663cc73584f1a0eb4e97e3db
@borkarsaish65 Please correct the url

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/formsController.js
> +	 * @api {get} /project/v1/forms/read/:_id
@borkarsaish65 Please correct the url

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/formsController.js
> +	 * @apiSampleRequest /project/v1/forms/read/663cc73584f1a0eb4e97e3db
@borkarsaish65 Please correct the url

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/formsController.js
> +        console.log(error)
@borkarsaish65 remove unwanted consoles

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on controllers/v1/formsController.js
> +				})
@borkarsaish65 validator are missing for all the  apis mentioned in this controller. Please check and add

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on module/forms/helper.js
> +				console.log(defaultOrgDetails,'defaultOrgDetails')
@borkarsaish65 remove consoles

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on generics/services/users.js
> +            console.log(url,'url')
@borkarsaish65 please remove consoles before raising  PR

2024-10-07 12:47 UTC, VISHNUDAS-tunerlabs commented on module/forms/helper.js
> +					console.log(defaultOrgId,'<--defaultOrgId')
@borkarsaish65 remove consoles

2024-10-07 14:47 UTC, borkarsaish65 commented on controllers/v1/formsController.js
> +	 * @api {post} /project/v1/forms/create
done

2024-10-08 04:43 UTC, VISHNUDAS-tunerlabs requested changes
Reiewed

2024-10-08 04:43 UTC, VISHNUDAS-tunerlabs commented on databaseQueries/forms.js
> +	 */
@borkarsaish65 Please add api configuration in the service if required

2024-10-08 05:28 UTC, VISHNUDAS-tunerlabs commented on constants/interface-routes/configs.json
> +        {
@borkarsaish65 update with /:id required right?

2024-10-08 05:50 UTC, VISHNUDAS-tunerlabs approved these changes

2024-10-08 05:51 UTC, merged